[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.2", features = ["derive"] }
axum = { version = "0.7.7", features = ["ws"] }
futures = "0.3.31"
bincode = "1.3"
tokio = "1.40"